Train:
  encoder_model: resnet152 # resnet18, resnet34, resnet50, resnet101, resnet152, densenet121, densenet161, densenet169, densenet201
  encoder_pretrained: True
  embed_size: 256
  hidden_size: 512
  lstm_layers: 1
  num_epochs: 3
  batch_size: 128
  num_workers: 2
  learning_rate: 0.005